export default {
    'group' : [
        {'name' : 'normal', 'label' : '通常時'},
        {'name' : 'qom', 'label' : 'QoM'},
        {'name' : 'battle', 'label' : '最終決戦'},
        {'name' : 'sc', 'label' : 'シンフォギアチャンス'},
    ],
    'tags' : [
        {'name' : 'horyu', 'label' : '保留', 'relation' : ['normal']},
        {'name' : 'zugara', 'label' : '図柄'},
        {'name' : 'rebaburu', 'label' : 'レバブル', 'relation' : ['normal']},
        {'name' : 'gearpendant', 'label' : 'ギアペン'},
        {'name' : 'giji', 'label' : '疑似連台詞', 'relation' : ['normal']},
        {'name' : 'logogimmick', 'label' : 'タイトルロゴ', 'relation' : ['normal', 'sc']},
        {'name' : 'display', 'label' : '画面分割', 'relation' : ['normal']},
        {'name' : 'team', 'label' : 'チームSU(3人)', 'relation' : ['normal']},
        {'name' : 'equalizer', 'label' : 'イコライザSU', 'relation' : ['normal']},
        {'name' : 'fine_well', 'label' : 'フィーネorウェル台詞', 'relation' : ['normal']},
        {'name' : 'urotaeruna', 'label' : 'うろたえるなッ！', 'relation' : ['normal']},
        {'name' : 'stage', 'label' : 'ステージ', 'relation' : ['normal']},
        {'name' : 'lamp', 'label' : '響ランプ', 'relation' : ['normal']},
        {'name' : 'music', 'label' : '楽曲', 'relation' : ['normal', 'sc']},
        {'name' : 'totsu', 'label' : '突響', 'relation' : ['normal']},
        {'name' : 'freez', 'label' : '唄ってはダメ', 'relation' : ['normal']},
        {'name' : 'kashi', 'label' : '歌詞前兆', 'relation' : ['normal']},
        {'name' : 'midoku', 'label' : '見得', 'relation' : ['normal']},
        {'name' : 'matou', 'label' : '纏う', 'relation' : ['normal']},
        {'name' : 'reachvoice', 'label' : 'リーチボイス', 'relation' : ['normal']},
        {'name' : 'chance', 'label' : '戦姫絶唱チャンス', 'relation' : ['normal']},
        {'name' : 'mail', 'label' : '未来メール', 'relation' : ['normal']},
        {'name' : 'revol', 'label' : 'レボリューションチャンス', 'relation' : ['normal']},
        {'name' : 'dato', 'label' : '○○だとぉ？', 'relation' : ['normal']},
        {'name' : 'syousan', 'label' : '勝算はあるのか？', 'relation' : ['normal']},
        {'name' : 'saitan', 'label' : '最短で真っ直ぐに一直線に', 'relation' : ['normal']},
        {'name' : 'reach', 'label' : 'リーチ', 'relation' : ['normal']},
        {'name' : 'seiei', 'label' : '聖詠ボーナスチャンス', 'relation' : ['normal']},
        {'name' : 's2ca', 'label' : 'S2CA', 'relation' : ['normal']},
        
        {'name' : '3key', 'label' : '3大キーポイント', 'relation' : ['normal']},
        {'name' : 'kakutei', 'label' : '確定パターン'},

        {'name' : 'sc-hibiki', 'label' : 'SC(響)', 'relation' : ['sc']},
        {'name' : 'sc-tsubasa', 'label' : 'SC(翼)', 'relation' : ['sc']},
        {'name' : 'sc-chris', 'label' : 'SC(クリス)', 'relation' : ['sc']},
        {'name' : 'sc-maria', 'label' : 'SC(マリア)', 'relation' : ['sc']},
        {'name' : 'sc-kirishira', 'label' : 'SC(切歌・調)', 'relation' : ['sc']},

        {'name' : 'action_roulette', 'label' : 'アクションルーレット', 'relation' : ['sc']},
        {'name' : 'chara_serifu', 'label' : 'キャラ決意', 'relation' : ['sc']},
        {'name' : 'chara_cutin', 'label' : 'キャラカットイン', 'relation' : ['sc']},
        {'name' : 'sc-last', 'label' : '最終変動(7回転目)', 'relation' : ['sc']},
        
        
    ],
};